name: Continuous Integration

on:
  push:
    branches-ignore:
      - "main"
      - "dev"
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build
